/**
 * Weltweite Länder- und Stadtdaten für den Lead-Scraper
 * Länder: ISO 3166-1 Alpha-2 Codes + deutsche Namen + Flaggen
 * Städte: Top-Städte pro Land (als Suchvorschläge im Formular)
 */

export const WORLD_COUNTRIES: { value: string; label: string; flag: string }[] = [
  { value: "AF", label: "Afghanistan", flag: "🇦🇫" },
  { value: "EG", label: "Ägypten", flag: "🇪🇬" },
  { value: "AL", label: "Albanien", flag: "🇦🇱" },
  { value: "DZ", label: "Algerien", flag: "🇩🇿" },
  { value: "AD", label: "Andorra", flag: "🇦🇩" },
  { value: "AO", label: "Angola", flag: "🇦🇴" },
  { value: "AR", label: "Argentinien", flag: "🇦🇷" },
  { value: "AM", label: "Armenien", flag: "🇦🇲" },
  { value: "AZ", label: "Aserbaidschan", flag: "🇦🇿" },
  { value: "ET", label: "Äthiopien", flag: "🇪🇹" },
  { value: "AU", label: "Australien", flag: "🇦🇺" },
  { value: "AT", label: "Österreich", flag: "🇦🇹" },
  { value: "BS", label: "Bahamas", flag: "🇧🇸" },
  { value: "BH", label: "Bahrain", flag: "🇧🇭" },
  { value: "BD", label: "Bangladesch", flag: "🇧🇩" },
  { value: "BB", label: "Barbados", flag: "🇧🇧" },
  { value: "BY", label: "Belarus", flag: "🇧🇾" },
  { value: "BE", label: "Belgien", flag: "🇧🇪" },
  { value: "BZ", label: "Belize", flag: "🇧🇿" },
  { value: "BJ", label: "Benin", flag: "🇧🇯" },
  { value: "BT", label: "Bhutan", flag: "🇧🇹" },
  { value: "BO", label: "Bolivien", flag: "🇧🇴" },
  { value: "BA", label: "Bosnien und Herzegowina", flag: "🇧🇦" },
  { value: "BW", label: "Botswana", flag: "🇧🇼" },
  { value: "BR", label: "Brasilien", flag: "🇧🇷" },
  { value: "BN", label: "Brunei", flag: "🇧🇳" },
  { value: "BG", label: "Bulgarien", flag: "🇧🇬" },
  { value: "BF", label: "Burkina Faso", flag: "🇧🇫" },
  { value: "BI", label: "Burundi", flag: "🇧🇮" },
  { value: "CV", label: "Cabo Verde", flag: "🇨🇻" },
  { value: "CL", label: "Chile", flag: "🇨🇱" },
  { value: "CN", label: "China", flag: "🇨🇳" },
  { value: "CR", label: "Costa Rica", flag: "🇨🇷" },
  { value: "CI", label: "Côte d'Ivoire", flag: "🇨🇮" },
  { value: "DK", label: "Dänemark", flag: "🇩🇰" },
  { value: "DE", label: "Deutschland", flag: "🇩🇪" },
  { value: "DO", label: "Dominikanische Republik", flag: "🇩🇴" },
  { value: "DJ", label: "Dschibuti", flag: "🇩🇯" },
  { value: "EC", label: "Ecuador", flag: "🇪🇨" },
  { value: "SV", label: "El Salvador", flag: "🇸🇻" },
  { value: "ER", label: "Eritrea", flag: "🇪🇷" },
  { value: "EE", label: "Estland", flag: "🇪🇪" },
  { value: "SZ", label: "Eswatini", flag: "🇸🇿" },
  { value: "FJ", label: "Fidschi", flag: "🇫🇯" },
  { value: "FI", label: "Finnland", flag: "🇫🇮" },
  { value: "FR", label: "Frankreich", flag: "🇫🇷" },
  { value: "GA", label: "Gabun", flag: "🇬🇦" },
  { value: "GM", label: "Gambia", flag: "🇬🇲" },
  { value: "GE", label: "Georgien", flag: "🇬🇪" },
  { value: "GH", label: "Ghana", flag: "🇬🇭" },
  { value: "GD", label: "Grenada", flag: "🇬🇩" },
  { value: "GR", label: "Griechenland", flag: "🇬🇷" },
  { value: "GT", label: "Guatemala", flag: "🇬🇹" },
  { value: "GN", label: "Guinea", flag: "🇬🇳" },
  { value: "GW", label: "Guinea-Bissau", flag: "🇬🇼" },
  { value: "GY", label: "Guyana", flag: "🇬🇾" },
  { value: "HT", label: "Haiti", flag: "🇭🇹" },
  { value: "HN", label: "Honduras", flag: "🇭🇳" },
  { value: "HK", label: "Hongkong", flag: "🇭🇰" },
  { value: "IN", label: "Indien", flag: "🇮🇳" },
  { value: "ID", label: "Indonesien", flag: "🇮🇩" },
  { value: "IQ", label: "Irak", flag: "🇮🇶" },
  { value: "IR", label: "Iran", flag: "🇮🇷" },
  { value: "IE", label: "Irland", flag: "🇮🇪" },
  { value: "IS", label: "Island", flag: "🇮🇸" },
  { value: "IL", label: "Israel", flag: "🇮🇱" },
  { value: "IT", label: "Italien", flag: "🇮🇹" },
  { value: "JM", label: "Jamaika", flag: "🇯🇲" },
  { value: "JP", label: "Japan", flag: "🇯🇵" },
  { value: "YE", label: "Jemen", flag: "🇾🇪" },
  { value: "JO", label: "Jordanien", flag: "🇯🇴" },
  { value: "KH", label: "Kambodscha", flag: "🇰🇭" },
  { value: "CM", label: "Kamerun", flag: "🇨🇲" },
  { value: "CA", label: "Kanada", flag: "🇨🇦" },
  { value: "KZ", label: "Kasachstan", flag: "🇰🇿" },
  { value: "QA", label: "Katar", flag: "🇶🇦" },
  { value: "KE", label: "Kenia", flag: "🇰🇪" },
  { value: "KG", label: "Kirgisistan", flag: "🇰🇬" },
  { value: "CO", label: "Kolumbien", flag: "🇨🇴" },
  { value: "CG", label: "Kongo", flag: "🇨🇬" },
  { value: "CD", label: "Kongo, Dem. Rep.", flag: "🇨🇩" },
  { value: "KR", label: "Korea, Süd-", flag: "🇰🇷" },
  { value: "HR", label: "Kroatien", flag: "🇭🇷" },
  { value: "CU", label: "Kuba", flag: "🇨🇺" },
  { value: "KW", label: "Kuwait", flag: "🇰🇼" },
  { value: "LA", label: "Laos", flag: "🇱🇦" },
  { value: "LS", label: "Lesotho", flag: "🇱🇸" },
  { value: "LV", label: "Lettland", flag: "🇱🇻" },
  { value: "LB", label: "Libanon", flag: "🇱🇧" },
  { value: "LR", label: "Liberia", flag: "🇱🇷" },
  { value: "LY", label: "Libyen", flag: "🇱🇾" },
  { value: "LI", label: "Liechtenstein", flag: "🇱🇮" },
  { value: "LT", label: "Litauen", flag: "🇱🇹" },
  { value: "LU", label: "Luxemburg", flag: "🇱🇺" },
  { value: "MG", label: "Madagaskar", flag: "🇲🇬" },
  { value: "MW", label: "Malawi", flag: "🇲🇼" },
  { value: "MY", label: "Malaysia", flag: "🇲🇾" },
  { value: "MV", label: "Malediven", flag: "🇲🇻" },
  { value: "ML", label: "Mali", flag: "🇲🇱" },
  { value: "MT", label: "Malta", flag: "🇲🇹" },
  { value: "MA", label: "Marokko", flag: "🇲🇦" },
  { value: "MR", label: "Mauretanien", flag: "🇲🇷" },
  { value: "MU", label: "Mauritius", flag: "🇲🇺" },
  { value: "MX", label: "Mexiko", flag: "🇲🇽" },
  { value: "MD", label: "Moldau", flag: "🇲🇩" },
  { value: "MC", label: "Monaco", flag: "🇲🇨" },
  { value: "MN", label: "Mongolei", flag: "🇲🇳" },
  { value: "ME", label: "Montenegro", flag: "🇲🇪" },
  { value: "MZ", label: "Mosambik", flag: "🇲🇿" },
  { value: "MM", label: "Myanmar", flag: "🇲🇲" },
  { value: "NA", label: "Namibia", flag: "🇳🇦" },
  { value: "NP", label: "Nepal", flag: "🇳🇵" },
  { value: "NZ", label: "Neuseeland", flag: "🇳🇿" },
  { value: "NI", label: "Nicaragua", flag: "🇳🇮" },
  { value: "NL", label: "Niederlande", flag: "🇳🇱" },
  { value: "NE", label: "Niger", flag: "🇳🇪" },
  { value: "NG", label: "Nigeria", flag: "🇳🇬" },
  { value: "MK", label: "Nordmazedonien", flag: "🇲🇰" },
  { value: "NO", label: "Norwegen", flag: "🇳🇴" },
  { value: "OM", label: "Oman", flag: "🇴🇲" },
  { value: "PK", label: "Pakistan", flag: "🇵🇰" },
  { value: "PA", label: "Panama", flag: "🇵🇦" },
  { value: "PG", label: "Papua-Neuguinea", flag: "🇵🇬" },
  { value: "PY", label: "Paraguay", flag: "🇵🇾" },
  { value: "PE", label: "Peru", flag: "🇵🇪" },
  { value: "PH", label: "Philippinen", flag: "🇵🇭" },
  { value: "PL", label: "Polen", flag: "🇵🇱" },
  { value: "PT", label: "Portugal", flag: "🇵🇹" },
  { value: "RW", label: "Ruanda", flag: "🇷🇼" },
  { value: "RO", label: "Rumänien", flag: "🇷🇴" },
  { value: "RU", label: "Russland", flag: "🇷🇺" },
  { value: "ZM", label: "Sambia", flag: "🇿🇲" },
  { value: "SM", label: "San Marino", flag: "🇸🇲" },
  { value: "SA", label: "Saudi-Arabien", flag: "🇸🇦" },
  { value: "SE", label: "Schweden", flag: "🇸🇪" },
  { value: "CH", label: "Schweiz", flag: "🇨🇭" },
  { value: "SN", label: "Senegal", flag: "🇸🇳" },
  { value: "RS", label: "Serbien", flag: "🇷🇸" },
  { value: "SC", label: "Seychellen", flag: "🇸🇨" },
  { value: "SL", label: "Sierra Leone", flag: "🇸🇱" },
  { value: "ZW", label: "Simbabwe", flag: "🇿🇼" },
  { value: "SG", label: "Singapur", flag: "🇸🇬" },
  { value: "SK", label: "Slowakei", flag: "🇸🇰" },
  { value: "SI", label: "Slowenien", flag: "🇸🇮" },
  { value: "SO", label: "Somalia", flag: "🇸🇴" },
  { value: "ES", label: "Spanien", flag: "🇪🇸" },
  { value: "LK", label: "Sri Lanka", flag: "🇱🇰" },
  { value: "ZA", label: "Südafrika", flag: "🇿🇦" },
  { value: "SD", label: "Sudan", flag: "🇸🇩" },
  { value: "SS", label: "Südsudan", flag: "🇸🇸" },
  { value: "SR", label: "Suriname", flag: "🇸🇷" },
  { value: "SY", label: "Syrien", flag: "🇸🇾" },
  { value: "TJ", label: "Tadschikistan", flag: "🇹🇯" },
  { value: "TZ", label: "Tansania", flag: "🇹🇿" },
  { value: "TH", label: "Thailand", flag: "🇹🇭" },
  { value: "TL", label: "Timor-Leste", flag: "🇹🇱" },
  { value: "TG", label: "Togo", flag: "🇹🇬" },
  { value: "TO", label: "Tonga", flag: "🇹🇴" },
  { value: "TT", label: "Trinidad und Tobago", flag: "🇹🇹" },
  { value: "TD", label: "Tschad", flag: "🇹🇩" },
  { value: "CZ", label: "Tschechien", flag: "🇨🇿" },
  { value: "TN", label: "Tunesien", flag: "🇹🇳" },
  { value: "TR", label: "Türkei", flag: "🇹🇷" },
  { value: "TM", label: "Turkmenistan", flag: "🇹🇲" },
  { value: "UG", label: "Uganda", flag: "🇺🇬" },
  { value: "UA", label: "Ukraine", flag: "🇺🇦" },
  { value: "HU", label: "Ungarn", flag: "🇭🇺" },
  { value: "UY", label: "Uruguay", flag: "🇺🇾" },
  { value: "UZ", label: "Usbekistan", flag: "🇺🇿" },
  { value: "VE", label: "Venezuela", flag: "🇻🇪" },
  { value: "AE", label: "Vereinigte Arabische Emirate", flag: "🇦🇪" },
  { value: "US", label: "Vereinigte Staaten", flag: "🇺🇸" },
  { value: "GB", label: "Vereinigtes Königreich", flag: "🇬🇧" },
  { value: "VN", label: "Vietnam", flag: "🇻🇳" },
  { value: "CF", label: "Zentralafrikanische Republik", flag: "🇨🇫" },
  { value: "CY", label: "Zypern", flag: "🇨🇾" },
];

/**
 * Stadtvorschläge pro Land (ISO-Code → Top-Städte).
 * Für DACH-Länder gelten die Bundesland/Kanton-Optionen aus types/leads.ts.
 * Hier nur Non-DACH-Länder.
 */
export const WORLD_CITY_SUGGESTIONS: Record<string, string[]> = {
  // ── Westeuropa ──
  GB: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Edinburgh", "Liverpool", "Bristol", "Sheffield", "Cardiff", "Newcastle upon Tyne", "Nottingham", "Leicester", "Belfast", "Coventry"],
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier", "Strasbourg", "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne", "Toulon", "Grenoble"],
  IT: ["Rom", "Mailand", "Neapel", "Turin", "Palermo", "Genua", "Bologna", "Florenz", "Bari", "Catania", "Venedig", "Verona", "Messina", "Padua", "Trieste"],
  ES: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Córdoba", "Valladolid", "Alicante", "Vigo", "Gijón"],
  PT: ["Lissabon", "Porto", "Braga", "Coimbra", "Funchal", "Setúbal", "Almada", "Amadora", "Vila Nova de Gaia"],
  NL: ["Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Breda", "Nijmegen", "Leiden", "Maastricht", "Zwolle"],
  BE: ["Brüssel", "Antwerpen", "Gent", "Brügge", "Lüttich", "Namur", "Löwen", "Mechelen", "Aalst", "Hasselt"],
  LU: ["Luxemburg", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords"],
  DK: ["Kopenhagen", "Aarhus", "Odense", "Aalborg", "Frederiksberg", "Esbjerg", "Randers", "Kolding"],
  SE: ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Linköping", "Västerås", "Örebro", "Norrköping", "Helsingborg", "Jönköping"],
  NO: ["Oslo", "Bergen", "Stavanger", "Trondheim", "Tromsø", "Fredrikstad", "Drammen", "Kristiansand"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio"],
  IS: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri"],
  MT: ["Valletta", "Birkirkara", "Qormi", "Mosta", "Naxxar"],
  CY: ["Nikosia", "Limassol", "Larnaka", "Famagusta", "Paphos"],
  MC: ["Monaco"],
  SM: ["San Marino"],
  LI: ["Vaduz", "Schaan", "Balzers", "Triesen"],
  AD: ["Andorra la Vella", "Escaldes-Engordany", "La Massana"],

  // ── Mitteleuropa ──
  PL: ["Warschau", "Krakau", "Lodz", "Breslau", "Posen", "Danzig", "Stettin", "Bydgoszcz", "Lublin", "Katowice", "Białystok", "Gdynia"],
  CZ: ["Prag", "Brünn", "Ostrava", "Pilsen", "Liberec", "Olmütz", "České Budějovice"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava"],
  HU: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr", "Nyíregyháza", "Kecskemét"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Novo Mesto", "Velenje"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Dubrovnik", "Pula", "Slavonski Brod"],
  BA: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  RS: ["Belgrad", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  ME: ["Podgorica", "Nikšić", "Herceg Novi", "Bar"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Tetovo"],
  AL: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan"],

  // ── Osteuropa / Baltikum ──
  RO: ["Bukarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Brașov", "Craiova", "Galați"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Stara Zagora", "Ruse", "Pleven"],
  UA: ["Kiew", "Charkiw", "Odessa", "Dnipro", "Lwiw", "Saporischschja"],
  MD: ["Chișinău", "Tiraspol", "Bălți", "Bender"],
  BY: ["Minsk", "Homel", "Mogilew", "Wizebsk", "Grodno", "Brest"],
  RU: ["Moskau", "Sankt Petersburg", "Nowosibirsk", "Jekaterinburg", "Kasan", "Nischni Nowgorod", "Samara", "Omsk", "Rostow am Don", "Ufa"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  GR: ["Athen", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Kavala"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin"],
  GE: ["Tiflis", "Batumi", "Kutaisi", "Rustavi", "Zugdidi"],
  AM: ["Jerewan", "Gjumri", "Wanadsor", "Abovjan"],
  AZ: ["Baku", "Ganja", "Sumqayit", "Mingachevir"],
  KZ: ["Almaty", "Nur-Sultan", "Schymkent", "Karaganda"],
  UZ: ["Taschkent", "Samarkand", "Namangan", "Buchara"],

  // ── Naher Osten ──
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras al-Khaimah", "Fujairah"],
  SA: ["Riad", "Dschidda", "Mekka", "Medina", "Dammam", "Khobar", "Taif", "Tabuk"],
  IL: ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Beer Sheva"],
  JO: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"],
  KW: ["Kuwait-Stadt", "Hawalli", "Salmiya", "Farwaniya"],
  QA: ["Doha", "Al-Rayyan", "Al Wakrah", "Al Khor"],
  BH: ["Manama", "Riffa", "Muharraq", "Hamad Town"],
  OM: ["Maskat", "Salalah", "Nizwa", "Sohar"],
  LB: ["Beirut", "Tripolis", "Sidon", "Tyros"],
  IQ: ["Bagdad", "Basra", "Mossul", "Erbil", "Sulaymaniyya"],
  IR: ["Teheran", "Maschhad", "Isfahan", "Karadsch", "Täbris", "Schiras"],

  // ── Nordamerika ──
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Nashville", "Boston", "Miami", "Atlanta", "Las Vegas", "Washington D.C.", "Minneapolis", "Portland", "Detroit"],
  CA: ["Toronto", "Montréal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Québec City", "Hamilton", "Kitchener", "London", "Halifax", "Victoria"],
  MX: ["Mexiko-Stadt", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Ciudad Juárez", "Cancún", "Mérida", "Querétaro", "San Luis Potosí"],

  // ── Mittelamerika / Karibik ──
  CR: ["San José", "Alajuela", "Desamparados", "San Carlos"],
  PA: ["Panama-Stadt", "San Miguelito", "Colón", "David"],
  GT: ["Guatemala-Stadt", "Mixco", "Villa Nueva", "Quetzaltenango"],
  HN: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"],
  SV: ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos"],
  NI: ["Managua", "León", "Masaya", "Chinandega"],
  DO: ["Santo Domingo", "Santiago", "Santo Domingo Este", "San Pedro de Macorís"],
  CU: ["Havanna", "Santiago de Cuba", "Camaguey", "Holguín"],
  JM: ["Kingston", "New Kingston", "Montego Bay", "Portmore"],
  TT: ["Port of Spain", "San Fernando", "Arima", "Chaguanas"],

  // ── Südamerika ──
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Campinas"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan"],
  CL: ["Santiago de Chile", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Arica"],
  CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga"],
  PE: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco"],
  EC: ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala"],
  VE: ["Caracas", "Maracaibo", "Valencia", "Maracay", "Barquisimeto"],
  BO: ["La Paz", "Cochabamba", "Santa Cruz", "Oruro", "Sucre"],
  PY: ["Asunción", "Ciudad del Este", "Encarnación", "Pedro Juan Caballero"],
  UY: ["Montevideo", "Salto", "Paysandú", "Las Piedras"],

  // ── Asien-Pazifik ──
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Wollongong", "Geelong", "Hobart", "Darwin"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Palmerston North"],
  JP: ["Tokio", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Yokohama", "Sendai"],
  CN: ["Peking", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Tianjin", "Wuhan", "Hangzhou", "Xi'an", "Nanjing", "Wuxi", "Suzhou"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon"],
  SG: ["Singapur"],
  HK: ["Hongkong"],
  TW: ["Taipeh", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  IN: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur", "Nagpur"],
  MY: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Petaling Jaya", "Shah Alam", "Kota Kinabalu"],
  TH: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Hat Yai", "Nakhon Ratchasima", "Udon Thani"],
  ID: ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Semarang", "Makassar", "Tangerang", "Depok", "Palembang", "Denpasar"],
  VN: ["Ho-Chi-Minh-Stadt", "Hanoi", "Da Nang", "Cần Thơ", "Hải Phòng", "Biên Hòa"],
  PH: ["Manila", "Quezon City", "Davao", "Cebu City", "Caloocan", "Zamboanga"],
  MM: ["Rangun", "Mandalay", "Nay Pyi Taw", "Mawlamyine"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  LK: ["Colombo", "Dehiwala", "Moratuwa", "Jaffna", "Kandy"],
  BD: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  PK: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Islamabad", "Hyderabad"],
  NP: ["Kathmandu", "Pokhara", "Lalitpur", "Birgunj", "Bharatpur"],

  // ── Afrika ──
  ZA: ["Johannesburg", "Kapstadt", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Nelspruit"],
  NG: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria"],
  EG: ["Kairo", "Alexandria", "Gizeh", "Schubra el-Chema", "Port Said", "Suez", "Luxor", "Assuan"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika"],
  TZ: ["Daressalam", "Sansibar", "Dodoma", "Mwanza", "Arusha", "Morogoro"],
  ET: ["Addis Abeba", "Dire Dawa", "Gondar", "Mekelle", "Adama"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman", "Cape Coast"],
  SN: ["Dakar", "Thiès", "Touba", "Kaolack", "Ziguinchor"],
  CI: ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro"],
  CM: ["Jaunde", "Douala", "Garoua", "Bafoussam", "Bamenda"],
  MA: ["Casablanca", "Fès", "Marrakesch", "Rabat", "Agadir", "Tanger", "Meknès"],
  TN: ["Tunis", "Sfax", "Sousse", "Monastir", "Kairouan", "Bizerte"],
  DZ: ["Algier", "Oran", "Constantine", "Annaba", "Blida", "Sétif"],
  LY: ["Tripolis", "Bengasi", "Misrata", "Tarhuna"],
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Mutare"],
  ZM: ["Lusaka", "Ndola", "Kitwe", "Kabwe"],
  NA: ["Windhoek", "Walvis Bay", "Swakopmund", "Rundu"],
  BW: ["Gaborone", "Francistown", "Mochudi", "Mogoditshane"],
  MZ: ["Maputo", "Matola", "Nampula", "Beira", "Quelimane"],
  MG: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa"],
  MU: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix"],
  SZ: ["Mbabane", "Manzini", "Lobamba"],
  LS: ["Maseru", "Teyateyaneng", "Mafeteng"],
  RW: ["Kigali", "Butare", "Gitarama", "Musanze"],
  UG: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"],
  TG: ["Lomé", "Sokodé", "Kara", "Kpalimé"],
  GN: ["Conakry", "N'Zérékoré", "Kindia", "Labé"],
  ML: ["Bamako", "Mopti", "Ségou", "Kayes"],
  BF: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora"],
};

/** Lookup: ISO-Code → Ländername auf Deutsch */
export function getCountryName(code: string): string {
  return WORLD_COUNTRIES.find((c) => c.value === code)?.label ?? code;
}

/** Lookup: ISO-Code → Flag-Emoji */
export function getCountryFlag(code: string): string {
  return WORLD_COUNTRIES.find((c) => c.value === code)?.flag ?? "";
}

/** DACH-Länder als Subset (für Rückwärtskompatibilität) */
export const DACH_COUNTRY_CODES = new Set(["AT", "DE", "CH"]);

/** Ob ein Land ein DACH-Land ist (hat Bundesland/Kanton-Struktur) */
export function isDACH(country: string): boolean {
  return DACH_COUNTRY_CODES.has(country);
}
